# Generated by Django 6.1 on 2026-08-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN', 'Login'), ('VIEW_PRODUCT', 'View Product'), ('ADD_TO_CART', 'Add To Cart'), ('CHECKOUT', 'Checkout'), ('PAYMENT_SUCCESS', 'Payment Success'), ('ORDER_COMPLETED', 'Order Completed')], max_length=30)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
