# Generated by Django 6.1 on 2026-08-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MIDTRANS', 'Payment Gateway'), ('MANUAL', 'Transfer Manual'), ('COD', 'Cash On Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('REVIEW', 'Review'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='WAITING', max_length=20)),
                ('snap_token', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.masterorder')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments.payment')),
            ],
        ),
    ]
